### PR TITLE
add pare report

### PR DESCRIPTION
**Pull request by edward-burn**

### CODE REVIEW

**Comment by edward-burn** [comment]
@mvankessel-EMC pkgdown is failing here when I try to add the PaRe report, but I suppose this might just be because we´ll need the code on the PaRe develop branch to get on to cran?

**Comment by mvankessel-EMC** [comment]
Can you re-install from CRAN? I pushed version 0.1.10 last Friday to CRAN.

**Comment by mvankessel-EMC** [comment]
Also looking at the backtrace:
```
Backtrace:
    ▆
 1. ├─PaRe::Repository$new(here::here())
 2. │ └─PaRe (local) initialize(...)
 3. │   └─base::normalizePath(path)
 4. │     └─base::path.expand(path)
 5. └─base::loadNamespace(x)
 6.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 7.     └─base (local) withOneRestart(expr, restarts[[1L]])
 8.       └─base (local) doWithOneRestart(return(expr), restart)
There were 14 warnings (use warnings() to see them)
```

Do you include `here::here()` in PatientProfiles? I don't see it listed in the description.

**Comment by mvankessel-EMC** [comment]
Ok, now it's failing on `magick`, which is included in the suggests of PaRe, but does not carry over to PatientProfiles. The same would go for `ggplot2`, `plotly`, etc. I don't think this is the ideal idea for including the report.

**Comment by mvankessel-EMC** [comment]
```
Quitting from lines 40-44 [getDefinedFunctionsPkg] (PareReport.Rmd)
--------------------------------------------------------------------------------
Error in `map()`:
ℹ In index: 4.
Caused by error in `render_rmarkdown()`:
! Failed to render RMarkdown
Caused by error:
! in callr subprocess.
Caused by error:
ℹ In argument: `size = lineEnd - lineStart + 1`.
Caused by error:
! object 'lineEnd' not found
Backtrace:
     ▆
  1. ├─defFuns %>% dplyr::mutate(size = lineEnd - lineStart + 1)
  2. ├─dplyr::mutate(., size = lineEnd - lineStart + 1)
  3. ├─dplyr:::mutate.data.frame(., size = lineEnd - lineStart + 1)
  4. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  5. │   ├─base::withCallingHandlers(...)
  6. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
  7. │     └─mask$eval_all_mutate(quo)
  8. │       └─dplyr (local) eval()
  9. └─base::.handleSimpleError(...)
 10.   └─dplyr (local) h(simpleError(msg, call))
 11.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
```

Looks similar to https://github.com/darwin-eu-dev/PaRe/issues/39. This is probably because of the rds-file it picks up mentioned in: https://github.com/darwin-eu-dev/PaRe/issues/42

**Comment by edward-burn** [comment]
thanks @mvankessel-EMC, getting closer :)

**Comment by mvankessel-EMC** [comment]
Out of curiosity, is there any specific reason as to why you store an rda-file in the `R`-folder, and not in `inst`?

**Comment by edward-burn** [comment]
Good point @mvankessel-EMC, @catalamarti maybe this should be elsewhere?

https://r-pkgs.org/data.html

**Comment by mvankessel-EMC** [comment]
> Is there any option to solve the issue with the pkgdown @edward-burn @mvankessel-EMC ?

From the logged lock-file I can't assert what version of PaRe is being used, but the rda-file issue should be fixed in [PaRe 0.1.11](https://cran.r-project.org/web/packages/PaRe/index.html) as I've [updated](https://github.com/darwin-eu-dev/PaRe/blob/main/R/R6-Repository.R#L242-L250) the pattern that detects the R-files.

**Pull request merged**
